#!/bin/sh /etc/rc.common

START=79
STOP=21
USE_PROCD=1

NAME="aria2"
CONF="/etc/aria2/aria2.conf"
PIDFILE="/var/run/aria2.pid"

start_service() {
    mkdir -p /tmp/downloads
    mkdir -p /etc/aria2

    [ ! -f "$CONF" ] && {
        cat > "$CONF" <<EOF
enable-rpc=true
rpc-listen-all=true
rpc-listen-port=6800
rpc-allow-origin-all=true
dir=/tmp/downloads
continue=true
file-allocation=none
EOF
    }

    procd_open_instance
    procd_set_param command /usr/bin/aria2c --conf-path="$CONF"
    procd_set_param respawn 3600 5 5
    procd_set_param pidfile "$PIDFILE"
    procd_close_instance
}

stop_service() {
    echo "Stopping aria2..."
}
